- name: "Test NetBox module"
  connection: local
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create tenant within NetBox with only required information
      netbox_tenant:
#        netbox_url: http://netbox.local
#        netbox_token: thisIsMyToken
        data:
          name: NetOps
          slug: netops
        state: present

